### ISSUE TITLE
Powering the led’s.

### ISSUE THREAD

**Issue by The-Torrent** [nicodeory/PianoLED#1]
Bro i’d Love to talk to you.
Discord The Torrent#5588
Skype removed
Email Removed

Regarding the actual thing:
My mate told me code is ‘inefficient’ I’ll expand on that once he has some time to go through it.

Powering the led’s - 5v at about 5 amp for the 74 is a hard to find power supply.

The 144led/meter question - do half the led’s go to waste and never light if I use this instead of will they light up in 2’s?
Will it spread them out and be lined up with the actual keys or just mess up?

Sorry not made too much sense here but would love to talk to you directly so I can better word my questions. I can probably get you some cash too if you want to do a partnership to put this into manufacture drop me a message.

Many thanks

**Comment by The-Torrent** [comment]
he said something about it needing more interrupts whatever that means.

anyway im gonna be building it soon anyway but that powering the led's thing is gonna be an issue for me you haven't made it clear how to power them and if there is any adverse effects using 144/m led strip instead will it still match up.

**Comment by nicolasdeory** [comment]
The LEDs will match up if you tweak the code accordingly, and if the LED strip aligns with the keys.

Regarding interrupts, they are not a viable option, because FastLED disables interrupts at certain intervals in order to be able to operate the WS2812B LEDs. Changing the LED strip to a faster one may fix the issue.

**Comment by The-Torrent** [comment]
Tweak the code? So major changes or just change some numbers.


Also I noticed you have said 74 lights marches 8 octaves.

A regular piano has 7 octaves does it not totalling 88 keys so that doesn’t make sense.

Also ordered a 74led/m strip.

Many thanks :)

**Comment by The-Torrent** [comment]
Just for onreaders, on line 135 there is a algorithm to work out the spacing, so no matter the density of the light strip the lights should match up.the method is confirmed to work with 60led/meter strip with some keys sharing lights (white keys). Will be testing with further densities and will post here for onreaders the results if it does not work and how to fix.
