### ISSUE TITLE
Schematic or PCB design

### ISSUE THREAD

**Issue by MarvinRucinski** [nicodeory/PianoLED#3]
Could you upload a schematic or your pcb design? On PCBWay no traces are visible on the board.
Even a screen shot of the schematic or the pcb with traces would be good enough for me.

**Comment by nicolasdeory** [comment]
![image](https://user-images.githubusercontent.com/1417708/115928882-226c5f80-a487-11eb-9a66-b129618918c3.png)

Let me know if you find this helpful, or if you need anything else.

**Comment by MarvinRucinski** [comment]
Thank you so much! It will be very helpful.
